#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2023.2 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : AMD Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Thu May 16 13:14:24 CST 2024
# SW Build 4029153 on Fri Oct 13 20:13:54 MDT 2023
#
# Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
# Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# simulate design
echo "xsim fsic_tb_behav -key {Behavioral:sim_1:Functional:fsic_tb} -tclbatch fsic_tb.tcl -protoinst "protoinst_files/bd_afc3.protoinst" -protoinst "protoinst_files/bd_a878.protoinst" -protoinst "protoinst_files/bd_a888.protoinst" -protoinst "protoinst_files/design_1.protoinst" -view /home/user/Documents/Code/ASoC/new_fsic/fsic_fpga/vivado/fsic_tb_behav.wcfg -log simulate.log"
xsim fsic_tb_behav -key {Behavioral:sim_1:Functional:fsic_tb} -tclbatch fsic_tb.tcl -protoinst "protoinst_files/bd_afc3.protoinst" -protoinst "protoinst_files/bd_a878.protoinst" -protoinst "protoinst_files/bd_a888.protoinst" -protoinst "protoinst_files/design_1.protoinst" -view /home/user/Documents/Code/ASoC/new_fsic/fsic_fpga/vivado/fsic_tb_behav.wcfg -log simulate.log

