-- ==============================================================
-- RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2021.2 (64-bit)
-- Version: 2021.2
-- Copyright (C) Copyright 1986-2021 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity userdma_paralleltostreamwithburst is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_continue : IN STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    m_axi_gmem1_AWVALID : OUT STD_LOGIC;
    m_axi_gmem1_AWREADY : IN STD_LOGIC;
    m_axi_gmem1_AWADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
    m_axi_gmem1_AWID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem1_AWLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_gmem1_AWSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem1_AWBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem1_AWLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem1_AWCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem1_AWPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem1_AWQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem1_AWREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem1_AWUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem1_WVALID : OUT STD_LOGIC;
    m_axi_gmem1_WREADY : IN STD_LOGIC;
    m_axi_gmem1_WDATA : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_gmem1_WSTRB : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem1_WLAST : OUT STD_LOGIC;
    m_axi_gmem1_WID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem1_WUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem1_ARVALID : OUT STD_LOGIC;
    m_axi_gmem1_ARREADY : IN STD_LOGIC;
    m_axi_gmem1_ARADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
    m_axi_gmem1_ARID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem1_ARLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_gmem1_ARSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem1_ARBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem1_ARLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem1_ARCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem1_ARPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem1_ARQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem1_ARREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem1_ARUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem1_RVALID : IN STD_LOGIC;
    m_axi_gmem1_RREADY : OUT STD_LOGIC;
    m_axi_gmem1_RDATA : IN STD_LOGIC_VECTOR (31 downto 0);
    m_axi_gmem1_RLAST : IN STD_LOGIC;
    m_axi_gmem1_RID : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem1_RFIFONUM : IN STD_LOGIC_VECTOR (8 downto 0);
    m_axi_gmem1_RUSER : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem1_RRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem1_BVALID : IN STD_LOGIC;
    m_axi_gmem1_BREADY : OUT STD_LOGIC;
    m_axi_gmem1_BRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem1_BID : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem1_BUSER : IN STD_LOGIC_VECTOR (0 downto 0);
    in_memory : IN STD_LOGIC_VECTOR (63 downto 0);
    in_en_clrsts : IN STD_LOGIC_VECTOR (0 downto 0);
    in_Img_width : IN STD_LOGIC_VECTOR (31 downto 0);
    in_m2s_len : IN STD_LOGIC_VECTOR (31 downto 0);
    outbuf_din : OUT STD_LOGIC_VECTOR (39 downto 0);
    outbuf_full_n : IN STD_LOGIC;
    outbuf_write : OUT STD_LOGIC;
    outcount48_din : OUT STD_LOGIC_VECTOR (31 downto 0);
    outcount48_full_n : IN STD_LOGIC;
    outcount48_write : OUT STD_LOGIC;
    m2s_enb_clrsts_c_din : OUT STD_LOGIC_VECTOR (0 downto 0);
    m2s_enb_clrsts_c_full_n : IN STD_LOGIC;
    m2s_enb_clrsts_c_write : OUT STD_LOGIC );
end;


architecture behav of userdma_paralleltostreamwithburst is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (4 downto 0) := "00001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (4 downto 0) := "00010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (4 downto 0) := "00100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (4 downto 0) := "01000";
    constant ap_ST_fsm_state5 : STD_LOGIC_VECTOR (4 downto 0) := "10000";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv64_0 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_10 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010000";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv33_1FFFFFFFF : STD_LOGIC_VECTOR (32 downto 0) := "111111111111111111111111111111111";
    constant ap_const_lv31_7FFFFFFF : STD_LOGIC_VECTOR (30 downto 0) := "1111111111111111111111111111111";
    constant ap_const_lv64_2 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000010";
    constant ap_const_lv32_3F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000111111";

attribute shreg_extract : string;
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_CS_fsm : STD_LOGIC_VECTOR (4 downto 0) := "00001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal first : STD_LOGIC_VECTOR (0 downto 0) := "1";
    signal m2s_len : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal outcount48_blk_n : STD_LOGIC;
    signal ap_CS_fsm_state5 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state5 : signal is "none";
    signal in_en_clrsts_read_read_fu_108_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal m2s_enb_clrsts_c_blk_n : STD_LOGIC;
    signal sub_i_i_fu_193_p2 : STD_LOGIC_VECTOR (32 downto 0);
    signal sub_i_i_reg_322 : STD_LOGIC_VECTOR (32 downto 0);
    signal trunc_ln86_fu_224_p1 : STD_LOGIC_VECTOR (30 downto 0);
    signal trunc_ln86_reg_333 : STD_LOGIC_VECTOR (30 downto 0);
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal sub_fu_230_p2 : STD_LOGIC_VECTOR (30 downto 0);
    signal sub_reg_339 : STD_LOGIC_VECTOR (30 downto 0);
    signal icmp_ln106_fu_237_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln2_reg_348 : STD_LOGIC_VECTOR (61 downto 0);
    signal grp_paralleltostreamwithburst_Pipeline_VITIS_LOOP_106_2_fu_148_ap_start : STD_LOGIC;
    signal grp_paralleltostreamwithburst_Pipeline_VITIS_LOOP_106_2_fu_148_ap_done : STD_LOGIC;
    signal grp_paralleltostreamwithburst_Pipeline_VITIS_LOOP_106_2_fu_148_ap_idle : STD_LOGIC;
    signal grp_paralleltostreamwithburst_Pipeline_VITIS_LOOP_106_2_fu_148_ap_ready : STD_LOGIC;
    signal grp_paralleltostreamwithburst_Pipeline_VITIS_LOOP_106_2_fu_148_m_axi_gmem1_AWVALID : STD_LOGIC;
    signal grp_paralleltostreamwithburst_Pipeline_VITIS_LOOP_106_2_fu_148_m_axi_gmem1_AWADDR : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_paralleltostreamwithburst_Pipeline_VITIS_LOOP_106_2_fu_148_m_axi_gmem1_AWID : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_paralleltostreamwithburst_Pipeline_VITIS_LOOP_106_2_fu_148_m_axi_gmem1_AWLEN : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_paralleltostreamwithburst_Pipeline_VITIS_LOOP_106_2_fu_148_m_axi_gmem1_AWSIZE : STD_LOGIC_VECTOR (2 downto 0);
    signal grp_paralleltostreamwithburst_Pipeline_VITIS_LOOP_106_2_fu_148_m_axi_gmem1_AWBURST : STD_LOGIC_VECTOR (1 downto 0);
    signal grp_paralleltostreamwithburst_Pipeline_VITIS_LOOP_106_2_fu_148_m_axi_gmem1_AWLOCK : STD_LOGIC_VECTOR (1 downto 0);
    signal grp_paralleltostreamwithburst_Pipeline_VITIS_LOOP_106_2_fu_148_m_axi_gmem1_AWCACHE : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_paralleltostreamwithburst_Pipeline_VITIS_LOOP_106_2_fu_148_m_axi_gmem1_AWPROT : STD_LOGIC_VECTOR (2 downto 0);
    signal grp_paralleltostreamwithburst_Pipeline_VITIS_LOOP_106_2_fu_148_m_axi_gmem1_AWQOS : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_paralleltostreamwithburst_Pipeline_VITIS_LOOP_106_2_fu_148_m_axi_gmem1_AWREGION : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_paralleltostreamwithburst_Pipeline_VITIS_LOOP_106_2_fu_148_m_axi_gmem1_AWUSER : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_paralleltostreamwithburst_Pipeline_VITIS_LOOP_106_2_fu_148_m_axi_gmem1_WVALID : STD_LOGIC;
    signal grp_paralleltostreamwithburst_Pipeline_VITIS_LOOP_106_2_fu_148_m_axi_gmem1_WDATA : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_paralleltostreamwithburst_Pipeline_VITIS_LOOP_106_2_fu_148_m_axi_gmem1_WSTRB : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_paralleltostreamwithburst_Pipeline_VITIS_LOOP_106_2_fu_148_m_axi_gmem1_WLAST : STD_LOGIC;
    signal grp_paralleltostreamwithburst_Pipeline_VITIS_LOOP_106_2_fu_148_m_axi_gmem1_WID : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_paralleltostreamwithburst_Pipeline_VITIS_LOOP_106_2_fu_148_m_axi_gmem1_WUSER : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_paralleltostreamwithburst_Pipeline_VITIS_LOOP_106_2_fu_148_m_axi_gmem1_ARVALID : STD_LOGIC;
    signal grp_paralleltostreamwithburst_Pipeline_VITIS_LOOP_106_2_fu_148_m_axi_gmem1_ARADDR : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_paralleltostreamwithburst_Pipeline_VITIS_LOOP_106_2_fu_148_m_axi_gmem1_ARID : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_paralleltostreamwithburst_Pipeline_VITIS_LOOP_106_2_fu_148_m_axi_gmem1_ARLEN : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_paralleltostreamwithburst_Pipeline_VITIS_LOOP_106_2_fu_148_m_axi_gmem1_ARSIZE : STD_LOGIC_VECTOR (2 downto 0);
    signal grp_paralleltostreamwithburst_Pipeline_VITIS_LOOP_106_2_fu_148_m_axi_gmem1_ARBURST : STD_LOGIC_VECTOR (1 downto 0);
    signal grp_paralleltostreamwithburst_Pipeline_VITIS_LOOP_106_2_fu_148_m_axi_gmem1_ARLOCK : STD_LOGIC_VECTOR (1 downto 0);
    signal grp_paralleltostreamwithburst_Pipeline_VITIS_LOOP_106_2_fu_148_m_axi_gmem1_ARCACHE : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_paralleltostreamwithburst_Pipeline_VITIS_LOOP_106_2_fu_148_m_axi_gmem1_ARPROT : STD_LOGIC_VECTOR (2 downto 0);
    signal grp_paralleltostreamwithburst_Pipeline_VITIS_LOOP_106_2_fu_148_m_axi_gmem1_ARQOS : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_paralleltostreamwithburst_Pipeline_VITIS_LOOP_106_2_fu_148_m_axi_gmem1_ARREGION : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_paralleltostreamwithburst_Pipeline_VITIS_LOOP_106_2_fu_148_m_axi_gmem1_ARUSER : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_paralleltostreamwithburst_Pipeline_VITIS_LOOP_106_2_fu_148_m_axi_gmem1_RREADY : STD_LOGIC;
    signal grp_paralleltostreamwithburst_Pipeline_VITIS_LOOP_106_2_fu_148_m_axi_gmem1_BREADY : STD_LOGIC;
    signal grp_paralleltostreamwithburst_Pipeline_VITIS_LOOP_106_2_fu_148_outbuf_din : STD_LOGIC_VECTOR (39 downto 0);
    signal grp_paralleltostreamwithburst_Pipeline_VITIS_LOOP_106_2_fu_148_outbuf_write : STD_LOGIC;
    signal grp_paralleltostreamwithburst_Pipeline_VITIS_LOOP_106_2_fu_148_m2s_len_o : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_paralleltostreamwithburst_Pipeline_VITIS_LOOP_106_2_fu_148_m2s_len_o_ap_vld : STD_LOGIC;
    signal count_1_reg_135 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal icmp_ln99_fu_212_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_paralleltostreamwithburst_Pipeline_VITIS_LOOP_106_2_fu_148_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state4 : signal is "none";
    signal ap_block_state1 : BOOLEAN;
    signal first_load_load_fu_173_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_sig_allocacmp_m2s_len_load : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_load_fu_166_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal idx_fu_88 : STD_LOGIC_VECTOR (63 downto 0);
    signal add_ln129_fu_269_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_block_state5 : BOOLEAN;
    signal icmp_ln131_fu_275_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal count_fu_92 : STD_LOGIC_VECTOR (31 downto 0);
    signal in_Img_width_cast_fu_189_p1 : STD_LOGIC_VECTOR (32 downto 0);
    signal shl_ln106_fu_243_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal add_ln106_fu_249_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal sext_ln129_fu_265_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (4 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_fsm_state2_blk : STD_LOGIC;
    signal ap_ST_fsm_state3_blk : STD_LOGIC;
    signal ap_ST_fsm_state4_blk : STD_LOGIC;
    signal ap_ST_fsm_state5_blk : STD_LOGIC;
    signal ap_condition_339 : BOOLEAN;
    signal ap_condition_238 : BOOLEAN;
    signal ap_ce_reg : STD_LOGIC;

    component userdma_paralleltostreamwithburst_Pipeline_VITIS_LOOP_106_2 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        m_axi_gmem1_AWVALID : OUT STD_LOGIC;
        m_axi_gmem1_AWREADY : IN STD_LOGIC;
        m_axi_gmem1_AWADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
        m_axi_gmem1_AWID : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem1_AWLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
        m_axi_gmem1_AWSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
        m_axi_gmem1_AWBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
        m_axi_gmem1_AWLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
        m_axi_gmem1_AWCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_gmem1_AWPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
        m_axi_gmem1_AWQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_gmem1_AWREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_gmem1_AWUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem1_WVALID : OUT STD_LOGIC;
        m_axi_gmem1_WREADY : IN STD_LOGIC;
        m_axi_gmem1_WDATA : OUT STD_LOGIC_VECTOR (31 downto 0);
        m_axi_gmem1_WSTRB : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_gmem1_WLAST : OUT STD_LOGIC;
        m_axi_gmem1_WID : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem1_WUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem1_ARVALID : OUT STD_LOGIC;
        m_axi_gmem1_ARREADY : IN STD_LOGIC;
        m_axi_gmem1_ARADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
        m_axi_gmem1_ARID : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem1_ARLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
        m_axi_gmem1_ARSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
        m_axi_gmem1_ARBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
        m_axi_gmem1_ARLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
        m_axi_gmem1_ARCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_gmem1_ARPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
        m_axi_gmem1_ARQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_gmem1_ARREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_gmem1_ARUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem1_RVALID : IN STD_LOGIC;
        m_axi_gmem1_RREADY : OUT STD_LOGIC;
        m_axi_gmem1_RDATA : IN STD_LOGIC_VECTOR (31 downto 0);
        m_axi_gmem1_RLAST : IN STD_LOGIC;
        m_axi_gmem1_RID : IN STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem1_RFIFONUM : IN STD_LOGIC_VECTOR (8 downto 0);
        m_axi_gmem1_RUSER : IN STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem1_RRESP : IN STD_LOGIC_VECTOR (1 downto 0);
        m_axi_gmem1_BVALID : IN STD_LOGIC;
        m_axi_gmem1_BREADY : OUT STD_LOGIC;
        m_axi_gmem1_BRESP : IN STD_LOGIC_VECTOR (1 downto 0);
        m_axi_gmem1_BID : IN STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem1_BUSER : IN STD_LOGIC_VECTOR (0 downto 0);
        outbuf_din : OUT STD_LOGIC_VECTOR (39 downto 0);
        outbuf_full_n : IN STD_LOGIC;
        outbuf_write : OUT STD_LOGIC;
        sext_ln106 : IN STD_LOGIC_VECTOR (61 downto 0);
        trunc_ln : IN STD_LOGIC_VECTOR (30 downto 0);
        sub : IN STD_LOGIC_VECTOR (30 downto 0);
        in_m2s_len : IN STD_LOGIC_VECTOR (31 downto 0);
        sub_i_i : IN STD_LOGIC_VECTOR (32 downto 0);
        count_1 : IN STD_LOGIC_VECTOR (30 downto 0);
        m2s_len_i : IN STD_LOGIC_VECTOR (31 downto 0);
        m2s_len_o : OUT STD_LOGIC_VECTOR (31 downto 0);
        m2s_len_o_ap_vld : OUT STD_LOGIC );
    end component;



begin
    grp_paralleltostreamwithburst_Pipeline_VITIS_LOOP_106_2_fu_148 : component userdma_paralleltostreamwithburst_Pipeline_VITIS_LOOP_106_2
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_paralleltostreamwithburst_Pipeline_VITIS_LOOP_106_2_fu_148_ap_start,
        ap_done => grp_paralleltostreamwithburst_Pipeline_VITIS_LOOP_106_2_fu_148_ap_done,
        ap_idle => grp_paralleltostreamwithburst_Pipeline_VITIS_LOOP_106_2_fu_148_ap_idle,
        ap_ready => grp_paralleltostreamwithburst_Pipeline_VITIS_LOOP_106_2_fu_148_ap_ready,
        m_axi_gmem1_AWVALID => grp_paralleltostreamwithburst_Pipeline_VITIS_LOOP_106_2_fu_148_m_axi_gmem1_AWVALID,
        m_axi_gmem1_AWREADY => ap_const_logic_0,
        m_axi_gmem1_AWADDR => grp_paralleltostreamwithburst_Pipeline_VITIS_LOOP_106_2_fu_148_m_axi_gmem1_AWADDR,
        m_axi_gmem1_AWID => grp_paralleltostreamwithburst_Pipeline_VITIS_LOOP_106_2_fu_148_m_axi_gmem1_AWID,
        m_axi_gmem1_AWLEN => grp_paralleltostreamwithburst_Pipeline_VITIS_LOOP_106_2_fu_148_m_axi_gmem1_AWLEN,
        m_axi_gmem1_AWSIZE => grp_paralleltostreamwithburst_Pipeline_VITIS_LOOP_106_2_fu_148_m_axi_gmem1_AWSIZE,
        m_axi_gmem1_AWBURST => grp_paralleltostreamwithburst_Pipeline_VITIS_LOOP_106_2_fu_148_m_axi_gmem1_AWBURST,
        m_axi_gmem1_AWLOCK => grp_paralleltostreamwithburst_Pipeline_VITIS_LOOP_106_2_fu_148_m_axi_gmem1_AWLOCK,
        m_axi_gmem1_AWCACHE => grp_paralleltostreamwithburst_Pipeline_VITIS_LOOP_106_2_fu_148_m_axi_gmem1_AWCACHE,
        m_axi_gmem1_AWPROT => grp_paralleltostreamwithburst_Pipeline_VITIS_LOOP_106_2_fu_148_m_axi_gmem1_AWPROT,
        m_axi_gmem1_AWQOS => grp_paralleltostreamwithburst_Pipeline_VITIS_LOOP_106_2_fu_148_m_axi_gmem1_AWQOS,
        m_axi_gmem1_AWREGION => grp_paralleltostreamwithburst_Pipeline_VITIS_LOOP_106_2_fu_148_m_axi_gmem1_AWREGION,
        m_axi_gmem1_AWUSER => grp_paralleltostreamwithburst_Pipeline_VITIS_LOOP_106_2_fu_148_m_axi_gmem1_AWUSER,
        m_axi_gmem1_WVALID => grp_paralleltostreamwithburst_Pipeline_VITIS_LOOP_106_2_fu_148_m_axi_gmem1_WVALID,
        m_axi_gmem1_WREADY => ap_const_logic_0,
        m_axi_gmem1_WDATA => grp_paralleltostreamwithburst_Pipeline_VITIS_LOOP_106_2_fu_148_m_axi_gmem1_WDATA,
        m_axi_gmem1_WSTRB => grp_paralleltostreamwithburst_Pipeline_VITIS_LOOP_106_2_fu_148_m_axi_gmem1_WSTRB,
        m_axi_gmem1_WLAST => grp_paralleltostreamwithburst_Pipeline_VITIS_LOOP_106_2_fu_148_m_axi_gmem1_WLAST,
        m_axi_gmem1_WID => grp_paralleltostreamwithburst_Pipeline_VITIS_LOOP_106_2_fu_148_m_axi_gmem1_WID,
        m_axi_gmem1_WUSER => grp_paralleltostreamwithburst_Pipeline_VITIS_LOOP_106_2_fu_148_m_axi_gmem1_WUSER,
        m_axi_gmem1_ARVALID => grp_paralleltostreamwithburst_Pipeline_VITIS_LOOP_106_2_fu_148_m_axi_gmem1_ARVALID,
        m_axi_gmem1_ARREADY => m_axi_gmem1_ARREADY,
        m_axi_gmem1_ARADDR => grp_paralleltostreamwithburst_Pipeline_VITIS_LOOP_106_2_fu_148_m_axi_gmem1_ARADDR,
        m_axi_gmem1_ARID => grp_paralleltostreamwithburst_Pipeline_VITIS_LOOP_106_2_fu_148_m_axi_gmem1_ARID,
        m_axi_gmem1_ARLEN => grp_paralleltostreamwithburst_Pipeline_VITIS_LOOP_106_2_fu_148_m_axi_gmem1_ARLEN,
        m_axi_gmem1_ARSIZE => grp_paralleltostreamwithburst_Pipeline_VITIS_LOOP_106_2_fu_148_m_axi_gmem1_ARSIZE,
        m_axi_gmem1_ARBURST => grp_paralleltostreamwithburst_Pipeline_VITIS_LOOP_106_2_fu_148_m_axi_gmem1_ARBURST,
        m_axi_gmem1_ARLOCK => grp_paralleltostreamwithburst_Pipeline_VITIS_LOOP_106_2_fu_148_m_axi_gmem1_ARLOCK,
        m_axi_gmem1_ARCACHE => grp_paralleltostreamwithburst_Pipeline_VITIS_LOOP_106_2_fu_148_m_axi_gmem1_ARCACHE,
        m_axi_gmem1_ARPROT => grp_paralleltostreamwithburst_Pipeline_VITIS_LOOP_106_2_fu_148_m_axi_gmem1_ARPROT,
        m_axi_gmem1_ARQOS => grp_paralleltostreamwithburst_Pipeline_VITIS_LOOP_106_2_fu_148_m_axi_gmem1_ARQOS,
        m_axi_gmem1_ARREGION => grp_paralleltostreamwithburst_Pipeline_VITIS_LOOP_106_2_fu_148_m_axi_gmem1_ARREGION,
        m_axi_gmem1_ARUSER => grp_paralleltostreamwithburst_Pipeline_VITIS_LOOP_106_2_fu_148_m_axi_gmem1_ARUSER,
        m_axi_gmem1_RVALID => m_axi_gmem1_RVALID,
        m_axi_gmem1_RREADY => grp_paralleltostreamwithburst_Pipeline_VITIS_LOOP_106_2_fu_148_m_axi_gmem1_RREADY,
        m_axi_gmem1_RDATA => m_axi_gmem1_RDATA,
        m_axi_gmem1_RLAST => m_axi_gmem1_RLAST,
        m_axi_gmem1_RID => m_axi_gmem1_RID,
        m_axi_gmem1_RFIFONUM => m_axi_gmem1_RFIFONUM,
        m_axi_gmem1_RUSER => m_axi_gmem1_RUSER,
        m_axi_gmem1_RRESP => m_axi_gmem1_RRESP,
        m_axi_gmem1_BVALID => ap_const_logic_0,
        m_axi_gmem1_BREADY => grp_paralleltostreamwithburst_Pipeline_VITIS_LOOP_106_2_fu_148_m_axi_gmem1_BREADY,
        m_axi_gmem1_BRESP => ap_const_lv2_0,
        m_axi_gmem1_BID => ap_const_lv1_0,
        m_axi_gmem1_BUSER => ap_const_lv1_0,
        outbuf_din => grp_paralleltostreamwithburst_Pipeline_VITIS_LOOP_106_2_fu_148_outbuf_din,
        outbuf_full_n => outbuf_full_n,
        outbuf_write => grp_paralleltostreamwithburst_Pipeline_VITIS_LOOP_106_2_fu_148_outbuf_write,
        sext_ln106 => trunc_ln2_reg_348,
        trunc_ln => trunc_ln86_reg_333,
        sub => sub_reg_339,
        in_m2s_len => in_m2s_len,
        sub_i_i => sub_i_i_reg_322,
        count_1 => trunc_ln86_reg_333,
        m2s_len_i => m2s_len,
        m2s_len_o => grp_paralleltostreamwithburst_Pipeline_VITIS_LOOP_106_2_fu_148_m2s_len_o,
        m2s_len_o_ap_vld => grp_paralleltostreamwithburst_Pipeline_VITIS_LOOP_106_2_fu_148_m2s_len_o_ap_vld);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif ((not(((outcount48_full_n = ap_const_logic_0) and (in_en_clrsts = ap_const_lv1_0))) and (ap_const_logic_1 = ap_CS_fsm_state5) and ((icmp_ln131_fu_275_p2 = ap_const_lv1_1) or (in_en_clrsts_read_read_fu_108_p2 = ap_const_lv1_1)))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    grp_paralleltostreamwithburst_Pipeline_VITIS_LOOP_106_2_fu_148_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_paralleltostreamwithburst_Pipeline_VITIS_LOOP_106_2_fu_148_ap_start_reg <= ap_const_logic_0;
            else
                if (((ap_const_logic_1 = ap_CS_fsm_state3) and (icmp_ln106_fu_237_p2 = ap_const_lv1_1))) then 
                    grp_paralleltostreamwithburst_Pipeline_VITIS_LOOP_106_2_fu_148_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_paralleltostreamwithburst_Pipeline_VITIS_LOOP_106_2_fu_148_ap_ready = ap_const_logic_1)) then 
                    grp_paralleltostreamwithburst_Pipeline_VITIS_LOOP_106_2_fu_148_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    count_1_reg_135_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state2)) then
                if ((icmp_ln99_fu_212_p2 = ap_const_lv1_1)) then 
                    count_1_reg_135 <= ap_const_lv32_10;
                elsif ((icmp_ln99_fu_212_p2 = ap_const_lv1_0)) then 
                    count_1_reg_135 <= count_fu_92;
                end if;
            end if; 
        end if;
    end process;

    first_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not(((m2s_enb_clrsts_c_full_n = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1) or (ap_start = ap_const_logic_0))) and (first_load_load_fu_173_p1 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state1) and (in_en_clrsts = ap_const_lv1_0))) then 
                first <= ap_const_lv1_0;
            elsif (((icmp_ln99_fu_212_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
                first <= ap_const_lv1_1;
            end if; 
        end if;
    end process;

    idx_fu_88_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((in_en_clrsts = ap_const_lv1_0)) then
                if ((ap_const_boolean_1 = ap_condition_238)) then 
                    idx_fu_88 <= ap_const_lv64_0;
                elsif ((ap_const_boolean_1 = ap_condition_339)) then 
                    idx_fu_88 <= add_ln129_fu_269_p2;
                end if;
            end if; 
        end if;
    end process;

    m2s_len_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not(((m2s_enb_clrsts_c_full_n = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1) or (ap_start = ap_const_logic_0))) and (first_load_load_fu_173_p1 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state1) and (in_en_clrsts = ap_const_lv1_0))) then 
                m2s_len <= in_m2s_len;
            elsif (((grp_paralleltostreamwithburst_Pipeline_VITIS_LOOP_106_2_fu_148_m2s_len_o_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state4))) then 
                m2s_len <= grp_paralleltostreamwithburst_Pipeline_VITIS_LOOP_106_2_fu_148_m2s_len_o;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((not(((outcount48_full_n = ap_const_logic_0) and (in_en_clrsts = ap_const_lv1_0))) and (icmp_ln131_fu_275_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state5) and (in_en_clrsts = ap_const_lv1_0)) or (not(((m2s_enb_clrsts_c_full_n = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1) or (ap_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1) and (in_en_clrsts = ap_const_lv1_0)))) then
                count_fu_92 <= grp_load_fu_166_p1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state1) and (in_en_clrsts = ap_const_lv1_0))) then
                sub_i_i_reg_322 <= sub_i_i_fu_193_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state3)) then
                sub_reg_339 <= sub_fu_230_p2;
                trunc_ln86_reg_333 <= trunc_ln86_fu_224_p1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state3) and (icmp_ln106_fu_237_p2 = ap_const_lv1_1))) then
                trunc_ln2_reg_348 <= add_ln106_fu_249_p2(63 downto 2);
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_start, ap_done_reg, ap_CS_fsm, ap_CS_fsm_state1, in_en_clrsts, outcount48_full_n, m2s_enb_clrsts_c_full_n, ap_CS_fsm_state5, in_en_clrsts_read_read_fu_108_p2, ap_CS_fsm_state3, icmp_ln106_fu_237_p2, grp_paralleltostreamwithburst_Pipeline_VITIS_LOOP_106_2_fu_148_ap_done, ap_CS_fsm_state4, icmp_ln131_fu_275_p2)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if ((not(((m2s_enb_clrsts_c_full_n = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1) or (ap_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1) and (in_en_clrsts = ap_const_lv1_0))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                elsif ((not(((m2s_enb_clrsts_c_full_n = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1) or (ap_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1) and (in_en_clrsts_read_read_fu_108_p2 = ap_const_lv1_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state5;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                ap_NS_fsm <= ap_ST_fsm_state3;
            when ap_ST_fsm_state3 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state3) and (icmp_ln106_fu_237_p2 = ap_const_lv1_0))) then
                    ap_NS_fsm <= ap_ST_fsm_state5;
                else
                    ap_NS_fsm <= ap_ST_fsm_state4;
                end if;
            when ap_ST_fsm_state4 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state4) and (grp_paralleltostreamwithburst_Pipeline_VITIS_LOOP_106_2_fu_148_ap_done = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state5;
                else
                    ap_NS_fsm <= ap_ST_fsm_state4;
                end if;
            when ap_ST_fsm_state5 => 
                if ((not(((outcount48_full_n = ap_const_logic_0) and (in_en_clrsts = ap_const_lv1_0))) and (ap_const_logic_1 = ap_CS_fsm_state5) and ((icmp_ln131_fu_275_p2 = ap_const_lv1_1) or (in_en_clrsts_read_read_fu_108_p2 = ap_const_lv1_1)))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                elsif ((not(((outcount48_full_n = ap_const_logic_0) and (in_en_clrsts = ap_const_lv1_0))) and (icmp_ln131_fu_275_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state5) and (in_en_clrsts = ap_const_lv1_0))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state5;
                end if;
            when others =>  
                ap_NS_fsm <= "XXXXX";
        end case;
    end process;
    add_ln106_fu_249_p2 <= std_logic_vector(unsigned(shl_ln106_fu_243_p2) + unsigned(in_memory));
    add_ln129_fu_269_p2 <= std_logic_vector(signed(sext_ln129_fu_265_p1) + signed(idx_fu_88));
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);
    ap_CS_fsm_state4 <= ap_CS_fsm(3);
    ap_CS_fsm_state5 <= ap_CS_fsm(4);

    ap_ST_fsm_state1_blk_assign_proc : process(ap_start, ap_done_reg, m2s_enb_clrsts_c_full_n)
    begin
        if (((m2s_enb_clrsts_c_full_n = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1) or (ap_start = ap_const_logic_0))) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state2_blk <= ap_const_logic_0;
    ap_ST_fsm_state3_blk <= ap_const_logic_0;

    ap_ST_fsm_state4_blk_assign_proc : process(grp_paralleltostreamwithburst_Pipeline_VITIS_LOOP_106_2_fu_148_ap_done)
    begin
        if ((grp_paralleltostreamwithburst_Pipeline_VITIS_LOOP_106_2_fu_148_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state4_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state4_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_ST_fsm_state5_blk_assign_proc : process(in_en_clrsts, outcount48_full_n)
    begin
        if (((outcount48_full_n = ap_const_logic_0) and (in_en_clrsts = ap_const_lv1_0))) then 
            ap_ST_fsm_state5_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state5_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_block_state1_assign_proc : process(ap_start, ap_done_reg, m2s_enb_clrsts_c_full_n)
    begin
                ap_block_state1 <= ((m2s_enb_clrsts_c_full_n = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1) or (ap_start = ap_const_logic_0));
    end process;


    ap_block_state5_assign_proc : process(in_en_clrsts, outcount48_full_n)
    begin
                ap_block_state5 <= ((outcount48_full_n = ap_const_logic_0) and (in_en_clrsts = ap_const_lv1_0));
    end process;


    ap_condition_238_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_state1, m2s_enb_clrsts_c_full_n)
    begin
                ap_condition_238 <= (not(((m2s_enb_clrsts_c_full_n = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1) or (ap_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1));
    end process;


    ap_condition_339_assign_proc : process(in_en_clrsts, outcount48_full_n, ap_CS_fsm_state5, icmp_ln131_fu_275_p2)
    begin
                ap_condition_339 <= (not(((outcount48_full_n = ap_const_logic_0) and (in_en_clrsts = ap_const_lv1_0))) and (icmp_ln131_fu_275_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state5));
    end process;


    ap_done_assign_proc : process(ap_done_reg, in_en_clrsts, outcount48_full_n, ap_CS_fsm_state5, in_en_clrsts_read_read_fu_108_p2, icmp_ln131_fu_275_p2)
    begin
        if ((not(((outcount48_full_n = ap_const_logic_0) and (in_en_clrsts = ap_const_lv1_0))) and (ap_const_logic_1 = ap_CS_fsm_state5) and ((icmp_ln131_fu_275_p2 = ap_const_lv1_1) or (in_en_clrsts_read_read_fu_108_p2 = ap_const_lv1_1)))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_done_reg;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(in_en_clrsts, outcount48_full_n, ap_CS_fsm_state5, in_en_clrsts_read_read_fu_108_p2, icmp_ln131_fu_275_p2)
    begin
        if ((not(((outcount48_full_n = ap_const_logic_0) and (in_en_clrsts = ap_const_lv1_0))) and (ap_const_logic_1 = ap_CS_fsm_state5) and ((icmp_ln131_fu_275_p2 = ap_const_lv1_1) or (in_en_clrsts_read_read_fu_108_p2 = ap_const_lv1_1)))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_allocacmp_m2s_len_load_assign_proc : process(ap_CS_fsm_state1, in_en_clrsts, in_m2s_len, m2s_len, first_load_load_fu_173_p1)
    begin
        if (((first_load_load_fu_173_p1 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state1) and (in_en_clrsts = ap_const_lv1_0))) then 
            ap_sig_allocacmp_m2s_len_load <= in_m2s_len;
        else 
            ap_sig_allocacmp_m2s_len_load <= m2s_len;
        end if; 
    end process;

    first_load_load_fu_173_p1 <= first;

    grp_load_fu_166_p1_assign_proc : process(ap_CS_fsm_state1, in_en_clrsts, m2s_len, ap_CS_fsm_state5, ap_sig_allocacmp_m2s_len_load)
    begin
        if ((in_en_clrsts = ap_const_lv1_0)) then
            if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
                grp_load_fu_166_p1 <= m2s_len;
            elsif ((ap_const_logic_1 = ap_CS_fsm_state1)) then 
                grp_load_fu_166_p1 <= ap_sig_allocacmp_m2s_len_load;
            else 
                grp_load_fu_166_p1 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
            end if;
        else 
            grp_load_fu_166_p1 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;

    grp_paralleltostreamwithburst_Pipeline_VITIS_LOOP_106_2_fu_148_ap_start <= grp_paralleltostreamwithburst_Pipeline_VITIS_LOOP_106_2_fu_148_ap_start_reg;
    icmp_ln106_fu_237_p2 <= "1" when (signed(count_1_reg_135) > signed(ap_const_lv32_0)) else "0";
    icmp_ln131_fu_275_p2 <= "1" when (grp_load_fu_166_p1 = ap_const_lv32_0) else "0";
    icmp_ln99_fu_212_p2 <= "1" when (signed(count_fu_92) > signed(ap_const_lv32_10)) else "0";
    in_Img_width_cast_fu_189_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(in_Img_width),33));
    in_en_clrsts_read_read_fu_108_p2 <= in_en_clrsts;

    m2s_enb_clrsts_c_blk_n_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_state1, m2s_enb_clrsts_c_full_n)
    begin
        if ((not(((ap_done_reg = ap_const_logic_1) or (ap_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            m2s_enb_clrsts_c_blk_n <= m2s_enb_clrsts_c_full_n;
        else 
            m2s_enb_clrsts_c_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    m2s_enb_clrsts_c_din <= in_en_clrsts;

    m2s_enb_clrsts_c_write_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_state1, m2s_enb_clrsts_c_full_n)
    begin
        if ((not(((m2s_enb_clrsts_c_full_n = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1) or (ap_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            m2s_enb_clrsts_c_write <= ap_const_logic_1;
        else 
            m2s_enb_clrsts_c_write <= ap_const_logic_0;
        end if; 
    end process;

    m_axi_gmem1_ARADDR <= grp_paralleltostreamwithburst_Pipeline_VITIS_LOOP_106_2_fu_148_m_axi_gmem1_ARADDR;
    m_axi_gmem1_ARBURST <= grp_paralleltostreamwithburst_Pipeline_VITIS_LOOP_106_2_fu_148_m_axi_gmem1_ARBURST;
    m_axi_gmem1_ARCACHE <= grp_paralleltostreamwithburst_Pipeline_VITIS_LOOP_106_2_fu_148_m_axi_gmem1_ARCACHE;
    m_axi_gmem1_ARID <= grp_paralleltostreamwithburst_Pipeline_VITIS_LOOP_106_2_fu_148_m_axi_gmem1_ARID;
    m_axi_gmem1_ARLEN <= grp_paralleltostreamwithburst_Pipeline_VITIS_LOOP_106_2_fu_148_m_axi_gmem1_ARLEN;
    m_axi_gmem1_ARLOCK <= grp_paralleltostreamwithburst_Pipeline_VITIS_LOOP_106_2_fu_148_m_axi_gmem1_ARLOCK;
    m_axi_gmem1_ARPROT <= grp_paralleltostreamwithburst_Pipeline_VITIS_LOOP_106_2_fu_148_m_axi_gmem1_ARPROT;
    m_axi_gmem1_ARQOS <= grp_paralleltostreamwithburst_Pipeline_VITIS_LOOP_106_2_fu_148_m_axi_gmem1_ARQOS;
    m_axi_gmem1_ARREGION <= grp_paralleltostreamwithburst_Pipeline_VITIS_LOOP_106_2_fu_148_m_axi_gmem1_ARREGION;
    m_axi_gmem1_ARSIZE <= grp_paralleltostreamwithburst_Pipeline_VITIS_LOOP_106_2_fu_148_m_axi_gmem1_ARSIZE;
    m_axi_gmem1_ARUSER <= grp_paralleltostreamwithburst_Pipeline_VITIS_LOOP_106_2_fu_148_m_axi_gmem1_ARUSER;

    m_axi_gmem1_ARVALID_assign_proc : process(ap_CS_fsm_state3, icmp_ln106_fu_237_p2, grp_paralleltostreamwithburst_Pipeline_VITIS_LOOP_106_2_fu_148_m_axi_gmem1_ARVALID, ap_CS_fsm_state4)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state4) or ((ap_const_logic_1 = ap_CS_fsm_state3) and (icmp_ln106_fu_237_p2 = ap_const_lv1_1)))) then 
            m_axi_gmem1_ARVALID <= grp_paralleltostreamwithburst_Pipeline_VITIS_LOOP_106_2_fu_148_m_axi_gmem1_ARVALID;
        else 
            m_axi_gmem1_ARVALID <= ap_const_logic_0;
        end if; 
    end process;

    m_axi_gmem1_AWADDR <= ap_const_lv64_0;
    m_axi_gmem1_AWBURST <= ap_const_lv2_0;
    m_axi_gmem1_AWCACHE <= ap_const_lv4_0;
    m_axi_gmem1_AWID <= ap_const_lv1_0;
    m_axi_gmem1_AWLEN <= ap_const_lv32_0;
    m_axi_gmem1_AWLOCK <= ap_const_lv2_0;
    m_axi_gmem1_AWPROT <= ap_const_lv3_0;
    m_axi_gmem1_AWQOS <= ap_const_lv4_0;
    m_axi_gmem1_AWREGION <= ap_const_lv4_0;
    m_axi_gmem1_AWSIZE <= ap_const_lv3_0;
    m_axi_gmem1_AWUSER <= ap_const_lv1_0;
    m_axi_gmem1_AWVALID <= ap_const_logic_0;
    m_axi_gmem1_BREADY <= ap_const_logic_0;

    m_axi_gmem1_RREADY_assign_proc : process(ap_CS_fsm_state3, icmp_ln106_fu_237_p2, grp_paralleltostreamwithburst_Pipeline_VITIS_LOOP_106_2_fu_148_m_axi_gmem1_RREADY, ap_CS_fsm_state4)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state4) or ((ap_const_logic_1 = ap_CS_fsm_state3) and (icmp_ln106_fu_237_p2 = ap_const_lv1_1)))) then 
            m_axi_gmem1_RREADY <= grp_paralleltostreamwithburst_Pipeline_VITIS_LOOP_106_2_fu_148_m_axi_gmem1_RREADY;
        else 
            m_axi_gmem1_RREADY <= ap_const_logic_0;
        end if; 
    end process;

    m_axi_gmem1_WDATA <= ap_const_lv32_0;
    m_axi_gmem1_WID <= ap_const_lv1_0;
    m_axi_gmem1_WLAST <= ap_const_logic_0;
    m_axi_gmem1_WSTRB <= ap_const_lv4_0;
    m_axi_gmem1_WUSER <= ap_const_lv1_0;
    m_axi_gmem1_WVALID <= ap_const_logic_0;
    outbuf_din <= grp_paralleltostreamwithburst_Pipeline_VITIS_LOOP_106_2_fu_148_outbuf_din;

    outbuf_write_assign_proc : process(grp_paralleltostreamwithburst_Pipeline_VITIS_LOOP_106_2_fu_148_outbuf_write, ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            outbuf_write <= grp_paralleltostreamwithburst_Pipeline_VITIS_LOOP_106_2_fu_148_outbuf_write;
        else 
            outbuf_write <= ap_const_logic_0;
        end if; 
    end process;


    outcount48_blk_n_assign_proc : process(in_en_clrsts, outcount48_full_n, ap_CS_fsm_state5)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state5) and (in_en_clrsts = ap_const_lv1_0))) then 
            outcount48_blk_n <= outcount48_full_n;
        else 
            outcount48_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    outcount48_din <= count_1_reg_135;

    outcount48_write_assign_proc : process(in_en_clrsts, outcount48_full_n, ap_CS_fsm_state5)
    begin
        if ((not(((outcount48_full_n = ap_const_logic_0) and (in_en_clrsts = ap_const_lv1_0))) and (ap_const_logic_1 = ap_CS_fsm_state5) and (in_en_clrsts = ap_const_lv1_0))) then 
            outcount48_write <= ap_const_logic_1;
        else 
            outcount48_write <= ap_const_logic_0;
        end if; 
    end process;

        sext_ln129_fu_265_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(count_1_reg_135),64));

    shl_ln106_fu_243_p2 <= std_logic_vector(shift_left(unsigned(idx_fu_88),to_integer(unsigned('0' & ap_const_lv64_2(31-1 downto 0)))));
    sub_fu_230_p2 <= std_logic_vector(unsigned(trunc_ln86_fu_224_p1) + unsigned(ap_const_lv31_7FFFFFFF));
    sub_i_i_fu_193_p2 <= std_logic_vector(unsigned(in_Img_width_cast_fu_189_p1) + unsigned(ap_const_lv33_1FFFFFFFF));
    trunc_ln86_fu_224_p1 <= count_1_reg_135(31 - 1 downto 0);
end behav;
